=== davidprogil/CodeGenPus3/models/interface.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/interface" elementFormDefault="qualified" xmlns:sgi="http://www.example.org/interface">
    <xsd:complexType name="Interface">
    	<xsd:sequence>
    		<xsd:element name="description" type="xsd:string"></xsd:element>
    		<xsd:element name="types" type="sgi:Types"></xsd:element>
    		<xsd:element name="packets" type="sgi:Packets"></xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="name" type="xsd:string"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="Types">
    	<xsd:sequence>
    		<xsd:element name="enum" type="sgi:TypeEnum" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    		<xsd:element name="structureField" type="sgi:TypeStructureField" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>
    
    <xsd:complexType name="Packets">
    	<xsd:sequence>
    		<xsd:element name="packet" type="sgi:Packet" maxOccurs="unbounded" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="TypeEnum">
    	<xsd:sequence>
    		<xsd:element name="enumElement" type="sgi:TypeEnumElement" maxOccurs="unbounded" minOccurs="1"></xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
    	<xsd:attribute name="baseType" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>


    <xsd:complexType name="TypeEnumElement">
    	<xsd:attribute name="value" type="xsd:string" use="required"></xsd:attribute>
    	<xsd:attribute name="label" type="xsd:string" use="required"></xsd:attribute>
    	<xsd:attribute name="type" type="xsd:string"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="Field">
    	<xsd:sequence>
    		<xsd:element name="restrictionDetails" type="sgi:ValueRestictionDetails" maxOccurs="1" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
    	<xsd:attribute name="type" type="xsd:string" use="required"></xsd:attribute>
    	<xsd:attribute name="restriction" type="sgi:ValueRestrictionType"></xsd:attribute>
    	<xsd:attribute name="multiplicityFromField" type="xsd:string"></xsd:attribute>
		<xsd:attribute name="fixedMultiplicity" type="xsd:nonNegativeInteger" use="optional"></xsd:attribute>
    </xsd:complexType>

    <xsd:simpleType name="ValueRestrictionType">
    	<xsd:restriction base="xsd:string">
    		<xsd:enumeration value="FREE"></xsd:enumeration>
    		<xsd:enumeration value="FIXED"></xsd:enumeration>
    		<xsd:enumeration value="RANGE"></xsd:enumeration>
    		<xsd:enumeration value="ENUMERATION"></xsd:enumeration>
    	</xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="ValueRestictionDetails">
    	<xsd:sequence>
    		<xsd:element name="fixedValue" type="xsd:string" maxOccurs="1" minOccurs="0"></xsd:element>
    		<xsd:element name="maxExclusive" type="xsd:string" maxOccurs="1" minOccurs="0"></xsd:element>
    		<xsd:element name="maxInclusive" type="xsd:string" maxOccurs="1" minOccurs="0"></xsd:element>
    		<xsd:element name="minExclusive" type="xsd:string" maxOccurs="1" minOccurs="0"></xsd:element>
    		<xsd:element name="minInclusive" type="xsd:string" maxOccurs="1" minOccurs="0"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:element name="interface" type="sgi:Interface"></xsd:element>

    <xsd:complexType name="Packet">
    	<xsd:sequence>
    		<xsd:choice maxOccurs="unbounded" minOccurs="1">
                <xsd:element name="description" type="xsd:string"></xsd:element>
                <xsd:element name="structureField" type="sgi:StructureField"></xsd:element>
    			<xsd:element name="field" type="sgi:Field"></xsd:element>
    		</xsd:choice>
    	</xsd:sequence>
    	<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
    	<xsd:attribute name="id" type="xsd:string" use="required"></xsd:attribute>
    	<xsd:attribute name="isCommand" type="xsd:boolean" use="required"></xsd:attribute>
    	<xsd:attribute name="isToGenerate" type="xsd:string"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="StructureField">
    	<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
    	<xsd:attribute name="type" type="xsd:string" use="required"></xsd:attribute>
    	<xsd:attribute name="isUserCode" type="xsd:boolean"></xsd:attribute>
    	<xsd:attribute name="typeFromField" type="xsd:string"></xsd:attribute>
    	<xsd:attribute name="multiplicityFromField" type="xsd:string"></xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="TypeStructureField">
    	<xsd:sequence>
    		<xsd:element name="field" type="sgi:Field" maxOccurs="unbounded" minOccurs="1"></xsd:element>
    	</xsd:sequence>
    	<xsd:attribute name="name" type="xsd:string" use="required"></xsd:attribute>
    </xsd:complexType>
</xsd:schema>

=== davidprogil/CodeGenPus3/models/bootSw.xml
<?xml version="1.0" encoding="UTF-8"?>
<sgi:interface xmlns:sgi="http://www.example.org/interface"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/interface interface.xsd ">
	<sgi:description>Interface of the Boot SW</sgi:description>
	<sgi:types>
		<!-- Enumerations xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx -->
		<!-- General -->
		<sgi:enum name="EnumPktType" baseType="uint8">
			<sgi:enumElement label="PKT_TELEMETRY" value="0" type="null"></sgi:enumElement>
			<sgi:enumElement label="PKT_TELECOMMAND" value="1" type="null"></sgi:enumElement>
		</sgi:enum>
		<sgi:enum name="EnumBoolean" baseType="uint8">
			<sgi:enumElement label="BOL_FALSE" value="0" type="null"></sgi:enumElement>
			<sgi:enumElement label="BOL_TRUE" value="1" type="null"></sgi:enumElement>
		</sgi:enum>
		<sgi:enum name="EnumApid" baseType="uint16">
			<sgi:enumElement label="APID_BOOTSW" value="34" type="null"></sgi:enumElement>
			<sgi:enumElement label="APID_OBC" value="100" type="null"></sgi:enumElement>
		</sgi:enum>
		<sgi:enum name="EnumBootDevice" baseType="uint8">
			<sgi:enumElement label="BD_MSSW25_NOM" value="0" type="null"></sgi:enumElement>
			<sgi:enumElement label="BD_FPGAW25_NOM" value="1" type="null"></sgi:enumElement>
			<sgi:enumElement label="BD_MSSW25_RED" value="2" type="null"></sgi:enumElement>
			<sgi:enumElement label="BD_FPGAW25_RED" value="3" type="null"></sgi:enumElement>
		</sgi:enum>
		<sgi:enum name="EnumBootStatus" baseType="uint8">
			<sgi:enumElement label="BS_BOOTLOADER1_STARTED" value="0" type="null"></sgi:enumElement>
			<sgi:enumElement label="BS_DDR_TRAINING_STARTED" value="1" type="null"></sgi:enumElement>
			<sgi:enumElement label="BS_DDR_TRAINING_FAILED_REBOOT" value="2" type="null"></sgi:enumElement>
			<sgi:enumElement label="BS_BOOTLOADER2_STARTED" value="3" type="null"></sgi:enumElement>
			<sgi:enumElement label="BS_BOOTLOADER2_FAILED_REBOOT" value="4" type="null"></sgi:enumElement>
			<sgi:enumElement label="BS_LINUX_BOOT_STARTED" value="5" type="null"></sgi:enumElement>
			<sgi:enumElement label="BS_LINUX_BOOT_FAILED_REBOOT" value="6" type="null"></sgi:enumElement>
			<sgi:enumElement label="BS_LINUX_BOOT_SUCEEDED" value="7" type="null"></sgi:enumElement>
		</sgi:enum>
		<!-- Service 3 -->
		<sgi:enum name="EnumHkReportId" baseType="uint16">
			<sgi:enumElement label="HKID_ALL" value="0" type="null"></sgi:enumElement>
			<sgi:enumElement label="HKID_BOOT_HK" value="255" type="HkBootSw"></sgi:enumElement>
		</sgi:enum>
		<!-- Types xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx -->
		<sgi:structureField name="HkBootSw">
			<sgi:field name="bootDevice" type="EnumBootDevice"></sgi:field>
			<sgi:field name="bootStatus" type="EnumBootStatus"></sgi:field>
		</sgi:structureField>
	</sgi:types>
	<sgi:packets>
		<!-- Service 3 -->
		<!-- TM(3,25) -->
		<sgi:packet isCommand="false" name="HkReport" id="0x0319">
			<sgi:description>Informative Event</sgi:description>
			<sgi:structureField name="ccsdsPrimaryHeader" type="CCSDS_PrimaryHeader" isUserCode="true" />
			<sgi:structureField name="pusTmSecondaryHeader" type="PUS_TmSecondaryHeader" isUserCode="true"></sgi:structureField>
			<sgi:field name="structureId" type="EnumHkReportId"></sgi:field>
			<sgi:structureField name="hkData" type="variable" typeFromField="structureId"></sgi:structureField>
		</sgi:packet>
		

	</sgi:packets>
</sgi:interface>
